### ISSUE TITLE
Ansible module for chef-runner

### ISSUE THREAD

**Issue by mlafeldt** [mlafeldt/chef-runner#54]
The main goal of chef-runner is to provision remote machines via SSH. Ansible works in a similar way. So let's combine both to create the easiest Chef provisioner there is.

I already spiked an Ansible module which allows to provision a Vagrant machine. Here's a sample playbook:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Provision system with chef-runner
      chef_runner:
        vagrant_machine: default
        install_chef: "true"
        executable: "/usr/local/bin/chef-runner"
        working_dir: "/Users/mlafeldt/devel/projects/practicing-ruby-cookbook"
        run_list:
          - recipe[apt::default]
          - practicingruby::_deploy_user
```

This basically works, but I lack the knowledge to complete it the way I want.

## Problem 1

In particular, I don't know how to best support all the target systems chef-runner supports:

* Vagrant machines
* Test Kitchen instances
* plain SSH
* provision host system

I don't like the idea of having a separate configuration variable, e.g. `vagrant_machine`, for every supported system.

## Problem 2

To implement the most obvious use case with Ansible -- plain SSH -- I'd somehow have to pass Ansible's SSH connection settings (hostname, user, and other SSH options) to chef-runner. For this, I need to know if it's possible to access SSH connection settings for a host from Ansible modules.

(Instead of running chef-runner locally, I could instead run it on the remote host that is going to be provisioned. Unfortunately, this would require other Ruby tools to be installed on the remote host as well, e.g. for resolving cookbook dependencies. That's why I prefer `connection: local` here.)

**Comment by mlafeldt** [comment]
@gildegoma Maybe you can help me here?

**Comment by mlafeldt** [comment]
Need to check these:

* http://docs.ansible.com/playbooks_variables.html#information-discovered-from-systems-facts
* http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by mlafeldt** [comment]
As for problem 2, I found out that I can pass the SSH parameters from the hosts file to the modules, e.g.:

```yaml
- hosts: practicingruby
  connection: local
  gather_facts: no
  tasks:
    - name: Provision system with chef-runner
      chef_runner:
        host: "{{ ansible_ssh_user }}@{{ ansible_ssh_host }}"
        ssh_options:
          - "StrictHostKeyChecking no"
          - "IdentityFile {{ ansible_ssh_private_key_file }}"
          - "UserKnownHostsFile /dev/null"
        install_chef: "true"
        executable: "/usr/local/bin/chef-runner"
        working_dir: "/Users/mlafeldt/devel/projects/practicing-ruby-cookbook"
        run_list:
          - recipe[apt::default]
          - practicingruby::_deploy_user
```

However, I would still prefer retrieving these parameters inside the Ansible module. Still don't know how to do this, though.
